// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { getAuth } from "firebase/auth";
import { initializeApp } from "firebase/app";

const requiredServerFirebaseEnvVars = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
] as const;

for (const key of requiredServerFirebaseEnvVars) {
  if (!process.env[key]) {
    throw new Error(`Missing Firebase server environment variable: ${key}`);
  }
}

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID,
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
export const requireFirebaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const request = getRequest();

  if (!request?.headers) {
    throw new Response("Unauthorized: No request headers available", {
      status: 401,
    });
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Response("Unauthorized: No authorization header provided", {
      status: 401,
    });
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Response("Unauthorized: Only Bearer tokens are supported", {
      status: 401,
    });
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Response("Unauthorized: No token provided", { status: 401 });
  }

  try {
    // Verify the Firebase ID token
    const decodedToken = await auth.verifyIdToken(token);
    if (!decodedToken.uid) {
      throw new Response("Unauthorized: No user ID found in token", {
        status: 401,
      });
    }

    return next({
      context: {
        firebaseAuth: auth,
        userId: decodedToken.uid,
        claims: decodedToken,
      },
    });
  } catch (error) {
    throw new Response("Unauthorized: Invalid token", { status: 401 });
  }
});
