// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { getAuth } from "firebase/auth";
import { initializeApp } from "firebase/app";

// Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyA0Lh98DsRMDNm8WUzdXB8-p6arb57cDOA",
  authDomain: "madebyange1.firebaseapp.com",
  projectId: "madebyange1",
  storageBucket: "madebyange1.appspot.com",
  messagingSenderId: "603537844857",
  appId: "1:603537844857:web:f237a1881377daed9e42a8",
  measurementId: "G-YJJ5414K0P",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
export const requireFirebaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const request = getRequest();

  if (!request?.headers) {
    throw new Response("Unauthorized: No request headers available", {
      status: 401,
    });
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Response("Unauthorized: No authorization header provided", {
      status: 401,
    });
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Response("Unauthorized: Only Bearer tokens are supported", {
      status: 401,
    });
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Response("Unauthorized: No token provided", { status: 401 });
  }

  try {
    // Verify the Firebase ID token
    const decodedToken = await auth.verifyIdToken(token);
    if (!decodedToken.uid) {
      throw new Response("Unauthorized: No user ID found in token", {
        status: 401,
      });
    }

    return next({
      context: {
        firebaseAuth: auth,
        userId: decodedToken.uid,
        claims: decodedToken,
      },
    });
  } catch (error) {
    throw new Response("Unauthorized: Invalid token", { status: 401 });
  }
});
