// This file is automatically generated. Do not edit it directly.
// Server-side Firebase client for admin operations.
// Use this for admin operations in server functions and server routes only.
import { initializeApp, cert } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";

const requiredAdminEnvVars = [
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_CLIENT_EMAIL",
  "FIREBASE_PRIVATE_KEY",
] as const;

for (const key of requiredAdminEnvVars) {
  if (!process.env[key]) {
    throw new Error(`Missing Firebase admin environment variable: ${key}`);
  }
}

// Initialize Firebase Admin SDK
const adminApp = initializeApp({
  credential: cert({
    projectId: process.env.FIREBASE_PROJECT_ID,
    clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
    privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
  }),
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
});

// Initialize Firebase Admin services
export const adminAuth = getAuth(adminApp);
export const adminDb = getFirestore(adminApp);
export const adminStorage = getStorage(adminApp).bucket();

// Export a single object for convenience
export const firebaseAdmin = {
  auth: adminAuth,
  db: adminDb,
  storage: adminStorage,
};
