// This file is automatically generated. Do not edit it directly.
// Server-side Firebase client for admin operations.
// Use this for admin operations in server functions and server routes only.
import { initializeApp, cert } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";

// Initialize Firebase Admin SDK
const adminApp = initializeApp({
  credential: cert({
    projectId: "madebyange1",
    clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
    privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
  }),
  storageBucket: "madebyange1.appspot.com",
});

// Initialize Firebase Admin services
export const adminAuth = getAuth(adminApp);
export const adminDb = getFirestore(adminApp);
export const adminStorage = getStorage(adminApp).bucket();

// Export a single object for convenience
export const firebaseAdmin = {
  auth: adminAuth,
  db: adminDb,
  storage: adminStorage,
};
