// This file is automatically generated. Do not edit it directly.
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

// Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyA0Lh98DsRMDNm8WUzdXB8-p6arb57cDOA",
  authDomain: "madebyange1.firebaseapp.com",
  projectId: "madebyange1",
  storageBucket: "madebyange1.appspot.com",
  messagingSenderId: "603537844857",
  appId: "1:603537844857:web:f237a1881377daed9e42a8",
  measurementId: "G-YJJ5414K0P",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firebase services
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);

// Export a single object for convenience
export const firebase = {
  auth,
  db,
  storage,
};
