// This file is automatically generated. Do not edit it directly.
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

// Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyA0Lh98DsRMDNm8WUzdXB8-p6arb57cDOA",
  authDomain: "madebyange1.firebaseapp.com",
  projectId: "madebyange1",
  storageBucket: "madebyange1.appspot.com",
  messagingSenderId: "603537844857",
  appId: "1:603537844857:web:f237a1881377daed9e42a8",
  measurementId: "G-YJJ5414K0P",
};

let appInstance: ReturnType<typeof initializeApp> | null = null;
let authInstance: ReturnType<typeof getAuth> | null = null;
let dbInstance: ReturnType<typeof getFirestore> | null = null;
let storageInstance: ReturnType<typeof getStorage> | null = null;

function getAppInstance() {
  if (!appInstance) {
    appInstance = initializeApp(firebaseConfig);
  }

  return appInstance;
}

// Lazily initialize Firebase so public routes can render even if auth is never used.
export const firebase = {
  get auth() {
    authInstance ??= getAuth(getAppInstance());
    return authInstance;
  },
  get db() {
    dbInstance ??= getFirestore(getAppInstance());
    return dbInstance;
  },
  get storage() {
    storageInstance ??= getStorage(getAppInstance());
    return storageInstance;
  },
};
