/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPayslipsRouteImport } from './routes/_authenticated/payslips'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPayslipsIndexRouteImport } from './routes/_authenticated/payslips.index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees.index'
import { Route as AuthenticatedPayslipsPayslipIdRouteImport } from './routes/_authenticated/payslips.$payslipId'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees.new'
import { Route as AuthenticatedEmployeesEmployeeIdRouteImport } from './routes/_authenticated/employees.$employeeId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayslipsRoute = AuthenticatedPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayslipsIndexRoute =
  AuthenticatedPayslipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPayslipsRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedPayslipsPayslipIdRoute =
  AuthenticatedPayslipsPayslipIdRouteImport.update({
    id: '/$payslipId',
    path: '/$payslipId',
    getParentRoute: () => AuthenticatedPayslipsRoute,
  } as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdRoute =
  AuthenticatedEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/payroll': typeof AuthenticatedPayrollRoute
  '/payslips': typeof AuthenticatedPayslipsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/payslips/$payslipId': typeof AuthenticatedPayslipsPayslipIdRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/payslips/': typeof AuthenticatedPayslipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/payslips/$payslipId': typeof AuthenticatedPayslipsPayslipIdRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/payslips': typeof AuthenticatedPayslipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/payslips': typeof AuthenticatedPayslipsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/payslips/$payslipId': typeof AuthenticatedPayslipsPayslipIdRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/payslips/': typeof AuthenticatedPayslipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/dashboard'
    | '/employees'
    | '/payroll'
    | '/payslips'
    | '/settings'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/payslips/$payslipId'
    | '/employees/'
    | '/payslips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify'
    | '/dashboard'
    | '/payroll'
    | '/settings'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/payslips/$payslipId'
    | '/employees'
    | '/payslips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/verify'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/payroll'
    | '/_authenticated/payslips'
    | '/_authenticated/settings'
    | '/_authenticated/employees/$employeeId'
    | '/_authenticated/employees/new'
    | '/_authenticated/payslips/$payslipId'
    | '/_authenticated/employees/'
    | '/_authenticated/payslips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payslips': {
      id: '/_authenticated/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AuthenticatedPayslipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payslips/': {
      id: '/_authenticated/payslips/'
      path: '/'
      fullPath: '/payslips/'
      preLoaderRoute: typeof AuthenticatedPayslipsIndexRouteImport
      parentRoute: typeof AuthenticatedPayslipsRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/payslips/$payslipId': {
      id: '/_authenticated/payslips/$payslipId'
      path: '/$payslipId'
      fullPath: '/payslips/$payslipId'
      preLoaderRoute: typeof AuthenticatedPayslipsPayslipIdRouteImport
      parentRoute: typeof AuthenticatedPayslipsRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/employees/$employeeId': {
      id: '/_authenticated/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
  }
}

interface AuthenticatedEmployeesRouteChildren {
  AuthenticatedEmployeesEmployeeIdRoute: typeof AuthenticatedEmployeesEmployeeIdRoute
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
}

const AuthenticatedEmployeesRouteChildren: AuthenticatedEmployeesRouteChildren =
  {
    AuthenticatedEmployeesEmployeeIdRoute:
      AuthenticatedEmployeesEmployeeIdRoute,
    AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
    AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  }

const AuthenticatedEmployeesRouteWithChildren =
  AuthenticatedEmployeesRoute._addFileChildren(
    AuthenticatedEmployeesRouteChildren,
  )

interface AuthenticatedPayslipsRouteChildren {
  AuthenticatedPayslipsPayslipIdRoute: typeof AuthenticatedPayslipsPayslipIdRoute
  AuthenticatedPayslipsIndexRoute: typeof AuthenticatedPayslipsIndexRoute
}

const AuthenticatedPayslipsRouteChildren: AuthenticatedPayslipsRouteChildren = {
  AuthenticatedPayslipsPayslipIdRoute: AuthenticatedPayslipsPayslipIdRoute,
  AuthenticatedPayslipsIndexRoute: AuthenticatedPayslipsIndexRoute,
}

const AuthenticatedPayslipsRouteWithChildren =
  AuthenticatedPayslipsRoute._addFileChildren(
    AuthenticatedPayslipsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRouteWithChildren
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPayslipsRoute: typeof AuthenticatedPayslipsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRouteWithChildren,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPayslipsRoute: AuthenticatedPayslipsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
